# --- MAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0005

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.001
use_rnn: False
standardise_returns: False
standardise_rewards: False
q_nstep: 10 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "mappo"

t_max: 40000000



#save_model: True # Save the models to disk
# save_model_interval: 50000 # Save models after this many timesteps

hidden_dim: 128 # Size of hidden state for default rnn agent

checkpoint_path : "results/models/mappo_seed562348813_rware:rware-tiny-2ag-v1_2022-06-12 13:28:47.228321/"
evaluate: True
test_nepisode : 5

